### ISSUE TITLE
"Receive" line in account info shows wrong account

### ISSUE THREAD

**Issue by justdmitry** [nebyark/nano-blocks#1]
Account info screen in "receive" history line shows wrong account: current instead of tx source.

For example account [xrb_19koq5nufzum63uyb34xp4wq1jnqk4j545y9wxgp95o6ihaaitp8ymae6afm](https://nano.meltingice.net/explorer/account/xrb_19koq5nufzum63uyb34xp4wq1jnqk4j545y9wxgp95o6ihaaitp8ymae6afm/history) screen:

[screenshot.jpg](https://user-images.githubusercontent.com/3540597/42229240-afa9f626-7eee-11e8-96d0-28a55ad27f52.jpg)

"Receive" shows "xrb_19k...e6afm" which is wrong - it's current account. Should show "xrb_13r...1x7kr" (where nano came from).

**Comment by bk-promethean** [comment]
No longer an issue since https://github.com/nanocurrency/raiblocks/pull/820 was merged in.

**Comment by nebyark** [comment]
No longer an issue after https://github.com/nanocurrency/raiblocks/pull/820 was merged in.
