### ISSUE TITLE
QR code scan with amount trimming to 6 points of precision

### ISSUE THREAD

**Issue by nanoble-org** [nebyark/nano-blocks#14]
When scanning a QR code that has an amount coded in it where there are more then 6 points of precision in the amount, the app is cutting it off at 6 points, resulting in the incorrect amount.

**Comment by nebyark** [comment]
Fixed in https://github.com/nebyark/nano-blocks/pull/17

Currently doubles the amount of precision to 12. Having 30 points would cause some issues with how the amount is displayed in the UI, so arbitrarily keeping it at 12 for now.
