### ISSUE TITLE
Seed import shows 0 balance

### ISSUE THREAD

**Issue by warai17** [nebyark/nano-blocks#2]
When importing a seed with an existing balance (on one account), the account shows up but has 0 balance. When I tap the account, the balance then shows up and is shown consistently from then on.

The balance should show up immediately as to avoid confusion and concern. I ended up hitting "add account" a bunch of times thinking it was in another account before actually clicking into the first one.

Please see screenshots which show the process highlighting the issue.

![1](https://user-images.githubusercontent.com/38514525/42237440-c2d39284-7ecb-11e8-81cf-649aa2243f86.jpg)
![2](https://user-images.githubusercontent.com/38514525/42237441-c2e7795c-7ecb-11e8-8b52-bfc739be32d6.jpg)
![3](https://user-images.githubusercontent.com/38514525/42237442-c2fca0fc-7ecb-11e8-97b5-6945125a1790.jpg)

**Comment by nebyark** [comment]
Fixed in https://github.com/nebyark/nano-blocks/pull/18
