### ISSUE TITLE
Receive QR Code doesn't take Currency into consideration

### ISSUE THREAD

**Issue by gr0vity** [nebyark/nano-blocks#3]
**What I did** 

- Click 'Receive'
- Click 'Request Amount'
- Changed Currency from Nano to EUR
- Requested 5 EUR (QR Code changed)

**What I expected**
- After scanning the generated QR Code, the sender would be promted to send 5 EUR (~2.2 Nano)

**What happened**
- After scanning the generated QR Code, the sender was promted to send 5 Nano (~11.4EUR instead of 5EUR)

**Comment by nebyark** [comment]
Fixed in https://github.com/nebyark/nano-blocks/commit/1f5ba86c8deea1e0fcffb2337edd15d89f8cb1f6
