### ISSUE TITLE
Scroll issue in block viewer

### ISSUE THREAD

**Issue by warai17** [nebyark/nano-blocks#4]
On my iPhone 7, the block info is cut off on the bottom, even when scrolled all the way down. I have to pull the screen up to see the WORK value. Upon release of my thumb, it's back to how the screenshot looks. This seems to be an issue only with state blocks. You will see a screenshot of a legacy block (I think) which looks fine.

![state](https://user-images.githubusercontent.com/38514525/42239051-c11bfb48-7ed0-11e8-8628-4272971decfc.jpg)
![legacy](https://user-images.githubusercontent.com/38514525/42239050-c10a43e4-7ed0-11e8-8e34-533eb3a82451.jpg)

**Comment by nebyark** [comment]
Will be in next release.
